language: objective-c
osx_image: xcode7.2
xcode_workspace: FeedKit.xcworkspace
xcode_sdk: iphonesimulator9.2
env:
    global:
    - FRAMEWORK_NAME=FeedKit
    - IOS_FRAMEWORK_SCHEME="FeedKit iOS"
    - OSX_FRAMEWORK_SCHEME="FeedKit OSX"
    matrix:
        - DESTINATION="OS=8.1,name=iPhone 4S"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
        - DESTINATION="OS=8.2,name=iPhone 5"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
        - DESTINATION="OS=8.3,name=iPhone 5S"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
        - DESTINATION="OS=8.4,name=iPhone 6"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
        - DESTINATION="OS=9.0,name=iPhone 6 Plus"      SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
        - DESTINATION="OS=9.1,name=iPhone 6S"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
        - DESTINATION="OS=9.2,name=iPhone 6S Plus"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"
        - DESTINATION="arch=x86_64"                    SCHEME="$OSX_FRAMEWORK_SCHEME"     SDK="$OSX_SDK"
before_install:
    - brew update
    - brew install carthage
before_script:
    - carthage bootstrap
script:
    - ./fastlane/travis.sh
before_deploy:
    - carthage build --no-skip-current
    - carthage archive $FRAMEWORK_NAME
